.

diff --git a/.github/workflows/deploy_wheels.yml b/.github/workflows/deploy_wheels.yml
--- a/.github/workflows/deploy_wheels.yml
+++ b/.github/workflows/deploy_wheels.yml
@@ -26,11 +26,17 @@ jobs:
       run: |
         echo "Output something to the logs"
         echo "Trying to get acces to logs for ${{ github.run_id }}"
-        gh api /repos/kgd-al/abrain/actions/runs/3909767000 -q '.logs_url' || echo "Failed"
+        echo "gh api runs url"
+        gh api /repos/kgd-al/abrain/actions/runs/3909767000 -q '.' || echo "Failed"
+        echo
+        echo "gh api runs logs"
         gh api /repos/kgd-al/abrain/actions/runs/${{ github.run_id }}/logs > logs.zip  || echo "Failed"
+        echo
+        echo "gh run --log"
         gh run -R kgd-al/abrain view ${{ github.run_id }} --log-failed  || echo "Failed"
+        echo
         ls -lh
-        gh run cancel ${{ github.run_id }}
+        gh run -R kgd-al/abrain cancel ${{ github.run_id }}
 
   collect_targets:
     name: Collecting build targets
