.

diff --git a/.github/workflows/deploy_wheels.yml b/.github/workflows/deploy_wheels.yml
--- a/.github/workflows/deploy_wheels.yml
+++ b/.github/workflows/deploy_wheels.yml
@@ -276,14 +276,6 @@ jobs:
           echo "BADGES_COLORS=($colors )" >> $GITHUB_ENV
 
           
-      - name: /1/ list dist/*
-        run: |
-          echo "Contents of dist folder:"
-          ls dist/* || echo "error"
-          echo
-          echo "Looking for *.whl/*.targ.gz files"
-          find . -name "*.whl" -o -name "*.tar.gz"
-      
       - name: Upload summary to Wiki
         uses: SwiftDocOrg/github-wiki-publish-action@v1
         with:
@@ -293,11 +285,14 @@ jobs:
 
       - name: /1/ list dist/*
         run: |
+          echo "Contents of ~home:"
+          ls -lh
           echo "Contents of dist folder:"
           ls dist/* || echo "error"
           echo
           echo "Looking for *.whl/*.targ.gz files"
           find . -name "*.whl" -o -name "*.tar.gz"
+      
     
       - name: Build Badges
         uses: peterrhodesdev/build-a-badge@v1.3.1
@@ -307,6 +302,17 @@ jobs:
           label: ${{ env.BADGES_LABELS }}
           message: ${{ env.BADGES_MESSAGES }}
           color: ${{ env.BADGES_COLORS }}
+
+      - name: /2/ list dist/*
+        run: |
+          echo "Contents of ~home:"
+          ls -lh
+          echo "Contents of dist folder:"
+          ls dist/* || echo "error"
+          echo
+          echo "Looking for *.whl/*.targ.gz files"
+          find . -name "*.whl" -o -name "*.tar.gz"
+      
                     
     # For testing purposes, upload always
     # if: always()
@@ -314,14 +320,6 @@ jobs:
     # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
     #   alternatively, to publish when a GitHub Release is created, use the following rule:
     # if: github.event_name == 'release' && github.event.action == 'published'
-
-      - name: /1/ list dist/*
-        run: |
-          echo "Contents of dist folder:"
-          ls dist/* || echo "error"
-          echo
-          echo "Looking for *.whl/*.targ.gz files"
-          find . -name "*.whl" -o -name "*.tar.gz"
     
       - name: upload to TestPyPI
         uses: pypa/gh-action-pypi-publish@release/v1
