.

diff --git a/.github/workflows/deploy_wheels.yml b/.github/workflows/deploy_wheels.yml
--- a/.github/workflows/deploy_wheels.yml
+++ b/.github/workflows/deploy_wheels.yml
@@ -276,7 +276,13 @@ jobs:
           echo "BADGES_COLORS=($colors )" >> $GITHUB_ENV
 
           
-          
+      - name: /1/ list dist/*
+        run: |
+          echo "Contents of dist folder:"
+          ls dist/* || echo "error"
+          echo
+          echo "Looking for *.whl/*.targ.gz files"
+          find . -name "*.whl" -o -name "*.tar.gz"
       
       - name: Upload summary to Wiki
         uses: SwiftDocOrg/github-wiki-publish-action@v1
@@ -285,6 +291,14 @@ jobs:
         env:
           GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
 
+      - name: /1/ list dist/*
+        run: |
+          echo "Contents of dist folder:"
+          ls dist/* || echo "error"
+          echo
+          echo "Looking for *.whl/*.targ.gz files"
+          find . -name "*.whl" -o -name "*.tar.gz"
+    
       - name: Build Badges
         uses: peterrhodesdev/build-a-badge@v1.3.1
         with:
@@ -301,10 +315,10 @@ jobs:
     #   alternatively, to publish when a GitHub Release is created, use the following rule:
     # if: github.event_name == 'release' && github.event.action == 'published'
 
-      - name: list dist/*
+      - name: /1/ list dist/*
         run: |
           echo "Contents of dist folder:"
-          ls dist/*
+          ls dist/* || echo "error"
           echo
           echo "Looking for *.whl/*.targ.gz files"
           find . -name "*.whl" -o -name "*.tar.gz"
@@ -317,6 +331,7 @@ jobs:
           password: ${{ secrets.testpypi_password }}
           repository_url: https://test.pypi.org/legacy/
           verbose: true
+          skip_existing: true
 
       - name: upload to PyPI
         uses: pypa/gh-action-pypi-publish@release/v1
