.

diff --git a/.github/workflows/deploy_wheels.yml b/.github/workflows/deploy_wheels.yml
--- a/.github/workflows/deploy_wheels.yml
+++ b/.github/workflows/deploy_wheels.yml
@@ -53,8 +53,8 @@ jobs:
       - name: Faking build wheels
         run: |
           echo "Building ${{ matrix.build }}"
-          mkdir -pv wheelhouse
-          mkdir -pv logs
+          mkdir wheelhouse
+          mkdir logs
           echo "import random" > script.py
           echo "fail = (random.random() < .5)" >> script.py
           echo "if not fail:" >> script.py
@@ -65,7 +65,7 @@ jobs:
           echo "  print('Simulated error', msg)" >> script.py
           echo "  print('##[error]Process completed with exit code 1')" >> script.py
           echo "exit(fail)" >> script.py
-          python script.py 2>&1 | tee logs/${{ matrix.build }}.log
+          python3 script.py 2>&1 | tee logs/${{ matrix.build }}.log
           exit ${PIPESTATUS[0]}
                     
       #- uses: actions/checkout@v3
@@ -176,15 +176,16 @@ jobs:
                 mark=":x:"
                 
                 # Look it up in the logs
-                echo "## $build {#$build-details}" >> err_log
+                echo "## $build" >> err_log
                 grep -i '\berror\b' logs/*$build*.log \
                 | grep -v "##\[error\]Process completed" > tmp
                 cat tmp >> err_log
                 error=$(tail -n 1 tmp)
                 
-                build="[$build](#$build-details)"
+                build="[$build](#$build)"
               fi
               echo "| $mark | $build | $error |"
+              echo "| $mark | $build | $error |" >&2
             done | sort -t '|' -k3,3r
             cat err_log
           ) | tee -a $wiki $GITHUB_STEP_SUMMARY
