.

diff --git a/.github/workflows/deploy_wheels.yml b/.github/workflows/deploy_wheels.yml
--- a/.github/workflows/deploy_wheels.yml
+++ b/.github/workflows/deploy_wheels.yml
@@ -50,42 +50,43 @@ jobs:
       matrix: ${{ fromJson(needs.collect_targets.outputs.matrix) }}
 
     steps:
-      #- name: Faking build wheels
-        #run: |
-          #echo "Building ${{ matrix.build }}"
-          #mkdir wheelhouse
-          #mkdir logs
-          #echo "import random" > script.py
-          #echo "fail = (random.random() < .5)" >> script.py
-          #echo "if not fail:" >> script.py
-          #echo "  open('wheelhouse/${{ matrix.build }}.whl', 'w')" >> script.py
-          #echo "  print('Success')" >> script.py
-          #echo "else:" >> script.py
-          #echo "  msg=random.choice(['squares are round', 'err1', 'foo', 'bar'])" >> script.py
-          #echo "  print('Simulated error', msg)" >> script.py
-          #echo "  print('##[error]Process completed with exit code 1')" >> script.py
-          #echo "exit(fail)" >> script.py
-          #python3 script.py 2>&1 | tee logs/${{ matrix.build }}.log
-          #exit ${PIPESTATUS[0]}
-                    
-      - uses: actions/checkout@v3
-
-      - name: Build wheels
-        env:
-          CIBW_BUILD: ${{ matrix.build }}
-          CIBW_BUILD_VERBOSITY: -v
-          CIBW_TEST_EXTRAS: tests
-          CIBW_BEFORE_TEST: "pip install kaleido || echo 'No install candidates for kaleido'"
-          CIBW_BEFORE_TEST_LINUX: "yum install -y graphviz || apk add graphviz"
-          CIBW_BEFORE_TEST_MACOS: "brew install graphviz"
-          CIBW_BEFORE_TEST_WINDOWS: "choco install graphviz --no-progress"
-          CIBW_TEST_COMMAND: |
-            pytest {project}/tests -ra --small-scale --test-evolution
-        run: |
-          mkdir logs
-          pipx run cibuildwheel 2>&1 | tee logs/${{ matrix.build }}.log
-          exit ${PIPESTATUS[0]}
+      - name: Faking build wheels
         shell: bash
+        run: |
+          echo "Building ${{ matrix.build }}"
+          mkdir wheelhouse
+          mkdir logs
+          echo "import random" > script.py
+          echo "fail = (random.random() < .5)" >> script.py
+          echo "if not fail:" >> script.py
+          echo "  open('wheelhouse/${{ matrix.build }}.whl', 'w')" >> script.py
+          echo "  print('Success')" >> script.py
+          echo "else:" >> script.py
+          echo "  msg=random.choice(['squares are round', 'err1', 'foo', 'bar'])" >> script.py
+          echo "  print('Simulated error', msg)" >> script.py
+          echo "  print('##[error]Process completed with exit code 1')" >> script.py
+          echo "exit(fail)" >> script.py
+          python3 script.py 2>&1 | tee logs/${{ matrix.build }}.log
+          exit ${PIPESTATUS[0]}
+                    
+      #- uses: actions/checkout@v3
+
+      #- name: Build wheels
+        #env:
+          #CIBW_BUILD: ${{ matrix.build }}
+          #CIBW_BUILD_VERBOSITY: -v
+          #CIBW_TEST_EXTRAS: tests
+          #CIBW_BEFORE_TEST: "pip install kaleido || echo 'No install candidates for kaleido'"
+          #CIBW_BEFORE_TEST_LINUX: "yum install -y graphviz || apk add graphviz"
+          #CIBW_BEFORE_TEST_MACOS: "brew install graphviz"
+          #CIBW_BEFORE_TEST_WINDOWS: "choco install graphviz --no-progress"
+          #CIBW_TEST_COMMAND: |
+            #pytest {project}/tests -ra --small-scale --test-evolution
+        #shell: bash
+        #run: |
+          #mkdir logs
+          #pipx run cibuildwheel 2>&1 | tee logs/${{ matrix.build }}.log
+          #exit ${PIPESTATUS[0]}
           
       # --------
       # Unable to use github logs or redirect. Abandonned in favor of manual invocation
@@ -175,8 +176,8 @@ jobs:
             echo "# Build summary"
             echo "Successfully built $rate% of wheels"
             echo "## Details:"
-            echo "| Status | Build | Error |"
-            echo "| :----: | :---- | ----- |"
+            echo "| ID  | Ok  | Build | Error |"
+            echo "| :-: | :-: | :---- | ----- |"
             for build in $builds
             do
               mark=":heavy_check_mark:" 
@@ -185,6 +186,7 @@ jobs:
               # If wheel file was not uploaded -> error
               # x86 final name is different from built type
               build_search=$(sed 's/x86/*x86/' <<< $build)
+              echo find dist -name "*$build_search*.whl"
               wheel=$(find dist -name "*$build_search*.whl")
               if [ ! -z $wheel ]
               then
@@ -200,8 +202,7 @@ jobs:
                 build="[$build](#$build)"
               fi
               echo "| $mark | $build | $error |"
-              echo "| $mark | $build | $error |" >&2
-            done | sort -t '|' -k4,4
+            done | sort -t '|' -k4,4 | nl -s '|'
             cat err_log
           ) | tee -a $wiki $GITHUB_STEP_SUMMARY
       
