.

diff --git a/.github/workflows/deploy_wheels.yml b/.github/workflows/deploy_wheels.yml
--- a/.github/workflows/deploy_wheels.yml
+++ b/.github/workflows/deploy_wheels.yml
@@ -50,45 +50,45 @@ jobs:
       matrix: ${{ fromJson(needs.collect_targets.outputs.matrix) }}
 
     steps:
-      - name: Faking build wheels
-        shell: bash
-        run: |
-          echo "Building ${{ matrix.build }}"
-          mkdir wheelhouse
-          mkdir logs
-          log=logs/${{ matrix.build }}.log
-          echo "import random" > script.py
-          echo "fail = (random.random() < .5)" >> script.py
-          echo "if not fail:" >> script.py
-          echo "  open('wheelhouse/${{ matrix.build }}.whl', 'w')" >> script.py
-          echo "  print('Success')" >> script.py
-          echo "else:" >> script.py
-          echo "  msg=random.choice(['squares are round', 'err1', 'foo', 'bar'])" >> script.py
-          echo "  print('Simulated error', msg)" >> script.py
-          echo "  print('##[error]Process completed with exit code 1')" >> script.py
-          echo "exit(fail)" >> script.py
-          python3 script.py 2>&1 | tee $log
-          exit ${PIPESTATUS[0]}
-                    
-      #- uses: actions/checkout@v3
-
-      #- name: Build wheels
-        #env:
-          #CIBW_BUILD: ${{ matrix.build }}
-          #CIBW_BUILD_VERBOSITY: -v
-          #CIBW_TEST_EXTRAS: tests
-          #CIBW_BEFORE_TEST: "pip install kaleido || echo 'No install candidates for kaleido'"
-          #CIBW_BEFORE_TEST_LINUX: "yum install -y graphviz || apk add graphviz"
-          #CIBW_BEFORE_TEST_MACOS: "brew install graphviz"
-          #CIBW_BEFORE_TEST_WINDOWS: "choco install graphviz --no-progress"
-          #CIBW_TEST_COMMAND: |
-            #pytest {project}/tests -ra --small-scale --test-evolution
+      #- name: Faking build wheels
         #shell: bash
         #run: |
+          #echo "Building ${{ matrix.build }}"
+          #mkdir wheelhouse
           #mkdir logs
-          #pipx run cibuildwheel 2>&1 | tee logs/${{ matrix.build }}.log
-          #ls -lh .
+          #log=logs/${{ matrix.build }}.log
+          #echo "import random" > script.py
+          #echo "fail = (random.random() < .5)" >> script.py
+          #echo "if not fail:" >> script.py
+          #echo "  open('wheelhouse/${{ matrix.build }}.whl', 'w')" >> script.py
+          #echo "  print('Success')" >> script.py
+          #echo "else:" >> script.py
+          #echo "  msg=random.choice(['squares are round', 'err1', 'foo', 'bar'])" >> script.py
+          #echo "  print('Simulated error', msg)" >> script.py
+          #echo "  print('##[error]Process completed with exit code 1')" >> script.py
+          #echo "exit(fail)" >> script.py
+          #python3 script.py 2>&1 | tee $log
           #exit ${PIPESTATUS[0]}
+                    
+      - uses: actions/checkout@v3
+
+      - name: Build wheels
+        env:
+          CIBW_BUILD: ${{ matrix.build }}
+          CIBW_BUILD_VERBOSITY: -v
+          CIBW_TEST_EXTRAS: tests
+          CIBW_BEFORE_TEST: "pip install kaleido || echo 'No install candidates for kaleido'"
+          CIBW_BEFORE_TEST_LINUX: "yum install -y graphviz || apk add graphviz"
+          CIBW_BEFORE_TEST_MACOS: "brew install graphviz"
+          CIBW_BEFORE_TEST_WINDOWS: "choco install graphviz --no-progress"
+          CIBW_TEST_COMMAND: |
+            pytest {project}/tests -ra --small-scale --test-evolution
+        shell: bash
+        run: |
+          mkdir logs
+          pipx run cibuildwheel 2>&1 | tee logs/${{ matrix.build }}.log
+          ls -lh .
+          exit ${PIPESTATUS[0]}
           
       - uses: actions/upload-artifact@v3
         with:
@@ -158,10 +158,10 @@ jobs:
           wiki="wiki/wheels.md"
                     
           built_log=built.md
-          echo > $built_log
+          truncate -s 0 $built_log
 
           errs_log=errors.md
-          echo > $errs_log
+          truncate -s 0 $errs_log
 
           (
             for build in $builds
@@ -186,10 +186,10 @@ jobs:
                 error=$(tail -n $n tmp | tr -d '\n' | sed 's/$/\n/')
                 
                 build="[$build](#$build)"
-                echo "| :x: | $build | $error |" >> $built_log
+                echo "| :x: | $build | $error |" >> $errs_log
                 
               else
-                echo "| :heavy_check_mark: | $build |" >> $errs_log
+                echo "| :heavy_check_mark: | $build |" >> $built_log
               fi
             done
             
